server:
  port: 10000
  compression:
    enabled : true
    mime-types : application/json

logging:
  level:
    "com.huacai.AlermController" : trace
    "com.huacai.Service.*": trace
    "com.huacai.DAO.Impl.*": trace
    "com.huacai.DAO.*" : trace
    "org.springframework.web.client.RestTemplate" : trace
  file:
    name: AlermCenter.log
    max-history: 10
    max-size: 100MB

spring:
  datasource:
    url: jdbc:mysql://172.26.157.242:10000/alerm_center?serverTimezone=Asia/Shanghai&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: acenter
    password: Mysql12#

wechat:
  corpid: 1
  corpsecret: 1
  agentid: 1
  token-url: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  message-url: https://qyapi.weixin.qq.com/cgi-bin/message/send
  pre-message: "[From AlermCenter]"